global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitry_monakhov'
