version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: post_db
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    container_name: ui
    depends_on:
      - post_db
    ports:
      - ${PORT_EXT}:${PORT_INT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${VERSION_POST}
    container_name: post
    depends_on:
      - post_db
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    container_name: comment
    depends_on:
      - post_db
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
