kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: uXxKUGsJNHH52p+Suao+IWS+1IUKm8C6g/mlMNiIYvk=
      - identity: {}
